version: '3.8'

networks:
  team5-net:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: team5-prom
    ports:
      - "9290:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - team5-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: team5-grafana
    ports:
      - "3600:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=team5admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - team5-net
    restart: unless-stopped
    depends_on:
      - prometheus

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: node-exporter-team5
    ports:
      - "9105:9105"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--web.listen-address=:9105'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - team5-net
    restart: unless-stopped

volumes:
  grafana-storage: