version: "3.8"

services:
  # ─── Node Exporter (CPU/메모리/디스크/네트워크) ───
  node-exp:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: team5-node-exp
    network_mode: host
    restart: unless-stopped

  # ─── DCGM Exporter (GPU) ───
  gpu-exp:
    image: nvidia/dcgm-exporter:latest
    container_name: team5-gpu-exp
    network_mode: host
    privileged: true
    restart: unless-stopped

  # ─── Prometheus ───
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: team5-prom
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9500:9090"           # 호스트 9500 → 컨테이너 9090
    restart: unless-stopped

  # ─── Grafana ───
  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: team5-grafana
    env_file:
      - .env                  # GF_SECURITY_ADMIN_USER/PASSWORD
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3600:3000"           # 호스트 3600 → 컨테이너 3000
    restart: unless-stopped

volumes:
  prom_data:
  grafana_data: