# version: "3.8"  <-- 이 줄은 삭제하거나 주석 처리합니다 (최신 Docker Compose에서는 불필요)

services:
  node-exp:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: team5-node-exp
    # network_mode: host <-- node-exporter는 host 네트워크를 사용해도 괜찮지만,
    #                        Prometheus와의 일관성을 위해 또는 특정 이유가 없다면
    #                        기본 브릿지 네트워크를 사용하고 포트 매핑을 할 수도 있습니다.
    #                        일단은 기존 설정을 존중하여 유지하거나,
    #                        문제가 된다면 아래처럼 포트 매핑으로 변경 가능합니다.
    # ports:
    #   - "9105:9100" # 호스트 9105 -> 컨테이너 9100 (node_exporter 기본 포트)
    # command: '--web.listen-address=:9100' # 컨테이너 내부에서 9100 포트 사용
    # 위와 같이 network_mode:host 대신 포트매핑을 사용할 경우 prometheus.yml의 localhost:9105는 유지됩니다.
    # 지금은 기존 설정대로 network_mode: host 와 command: '--web.listen-address=:9105'를 사용한다고 가정하겠습니다.
    network_mode: host
    command: '--web.listen-address=:9105' # team5 전용 node-exporter는 9105 포트 사용
    restart: unless-stopped

  # gpu-exp 서비스는 사용하지 않기로 했으므로 주석 처리 또는 삭제
  # gpu-exp:
  #   image: nvidia/dcgm-exporter:latest
  #   container_name: team5-gpu-exp
  #   network_mode: host
  #   privileged: true
  #   restart: unless-stopped

  prometheus: # 서비스 이름을 'prom'으로 하셨다면 'prom'으로 유지
    image: prom/prometheus:v2.52.0
    container_name: team5-prom
    # network_mode: host  <-- 만약 이 줄이 있다면 반드시 삭제!!!
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9501:9090"           # 호스트 9500 → 컨테이너 9090 (Team5 전용)
                                # 이 설정은 올바릅니다! team4와 충돌하지 않습니다.
    restart: unless-stopped
    networks:
      - team5-net

  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: team5-grafana
    # network_mode: host <-- Grafana에도 이 설정이 있다면 삭제하는 것이 일반적입니다.
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3600:3000"           # 호스트 3600 → 컨테이너 3000 (Team5 전용)
    restart: unless-stopped
    networks:
      - team5-net

volumes:
  prom_data:
  grafana_data:

networks:
  team5-net:
    driver: bridge